# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    ports:
      - 3306:3306
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: bmi_calculator_db
      MYSQL_USER: bianco
      MYSQL_PASSWORD: bianco
      MYSQL_ROOT_PASSWORD: example